# Generated by Django 6.0.3 on 2026-03-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owasp', '0072_project_project_name_gin_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_url', models.URLField(max_length=500)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('PARTIAL', 'Partial Success')], default='SUCCESS', max_length=20)),
                ('duration', models.FloatField(blank=True, help_text='Duration in seconds', null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Scrape Log',
                'verbose_name_plural': 'Scrape Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
